services:
  # CanalGov app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: canalgov_app
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      # If the password is set during first docker-compose up, the system user password will be set to this value.
      # You can always set the system user password later by running `docker exec -it canalgov_app ./canalgov --set-system-user-password`.
      CANALGOV_SYSTEM_USER_PASSWORD: ${CANALGOV_SYSTEM_USER_PASSWORD:-}
      CANALGOV_DB__HOST: db
      CANALGOV_DB__PORT: 5432
      CANALGOV_DB__USER: ${POSTGRES_USER:-canalgov}
      CANALGOV_DB__PASSWORD: ${POSTGRES_PASSWORD:-canalgov}
      CANALGOV_DB__DATABASE: ${POSTGRES_DB:-canalgov}
      CANALGOV_REDIS__ADDRESS: redis:6379
    networks:
      - canalgov
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/canalgov/uploads:rw 
      - ./config.toml:/canalgov/config.toml
    command: [sh, -c, "./canalgov --install --idempotent-install --yes --config /canalgov/config.toml && ./canalgov --upgrade --yes --config /canalgov/config.toml && ./canalgov --config /canalgov/config.toml"]

  # PostgreSQL database
  db:
    image: postgres:17-alpine
    container_name: canalgov_db
    restart: unless-stopped
    networks:
      - canalgov
    ports:
      # Only bind on the local interface. To connect to Postgres externally, change this to 0.0.0.0
      - "127.0.0.1:5432:5432"
    environment:
      # Set these environment variables to configure the database, defaults to canalgov.
      POSTGRES_USER: ${POSTGRES_USER:-canalgov}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-canalgov} 
      POSTGRES_DB: ${POSTGRES_DB:-canalgov}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-canalgov} -d ${POSTGRES_DB:-canalgov}"]
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:7-alpine
    container_name: canalgov_redis
    restart: unless-stopped
    ports:
      # Only bind on the local interface.
      - "127.0.0.1:6379:6379"
    networks:
      - canalgov
    volumes:
      - redis-data:/data

networks:
  canalgov:

volumes:
  postgres-data:
  redis-data:
